// Auto-generated by scripts/generate-v131-tests.mjs
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { scan } from "ciphersins";

describe("CS-V131 reporting exhaustive", () => {
	it("CS-V131-REP-001 json CS-JWT-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string) { return jwt.decode(t); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-01");
			expect(finding?.helpUrl).toContain("CS-JWT-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-002 sarif CS-JWT-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string) { return jwt.decode(t); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-01");
			expect(finding?.helpUrl).toContain("CS-JWT-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-003 json CS-JWT-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) { return jwt.verify(t, s); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-02");
			expect(finding?.helpUrl).toContain("CS-JWT-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-004 sarif CS-JWT-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) { return jwt.verify(t, s); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-02");
			expect(finding?.helpUrl).toContain("CS-JWT-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-005 json CS-JWT-03", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) { return jwt.verify(t, s, { algorithms: ["none"] }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-03");
			expect(finding?.helpUrl).toContain("CS-JWT-03");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-006 sarif CS-JWT-03", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) { return jwt.verify(t, s, { algorithms: ["none"] }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-03");
			expect(finding?.helpUrl).toContain("CS-JWT-03");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-007 json CS-JWT-04", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) { return jwt.verify(t, s, { ignoreExpiration: true }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-04");
			expect(finding?.helpUrl).toContain("CS-JWT-04");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-008 sarif CS-JWT-04", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) { return jwt.verify(t, s, { ignoreExpiration: true }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-04");
			expect(finding?.helpUrl).toContain("CS-JWT-04");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-009 json CS-JWT-05", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) { return jwt.sign(p, s); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-05");
			expect(finding?.helpUrl).toContain("CS-JWT-05");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-010 sarif CS-JWT-05", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) { return jwt.sign(p, s); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-05");
			expect(finding?.helpUrl).toContain("CS-JWT-05");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-011 json CS-JWT-06", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) { return jwt.sign(p, s, { noTimestamp: true }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-06");
			expect(finding?.helpUrl).toContain("CS-JWT-06");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-012 sarif CS-JWT-06", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) { return jwt.sign(p, s, { noTimestamp: true }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-JWT-06");
			expect(finding?.helpUrl).toContain("CS-JWT-06");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-013 json CS-CMP-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import crypto from "crypto";\nexport function f(token: string, expected: string) { return token === expected; }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-CMP-01");
			expect(finding?.helpUrl).toContain("CS-CMP-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-014 sarif CS-CMP-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import crypto from "crypto";\nexport function f(token: string, expected: string) { return token === expected; }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-CMP-01");
			expect(finding?.helpUrl).toContain("CS-CMP-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-015 json CS-RNG-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			"export function generateToken() { return Math.random(); }\n",
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-RNG-01");
			expect(finding?.helpUrl).toContain("CS-RNG-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-016 sarif CS-RNG-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			"export function generateToken() { return Math.random(); }\n",
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-RNG-01");
			expect(finding?.helpUrl).toContain("CS-RNG-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-017 json CS-RNG-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { randomBytes } from "crypto";\nexport function generateSessionToken() { return randomBytes(8); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-RNG-02");
			expect(finding?.helpUrl).toContain("CS-RNG-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-018 sarif CS-RNG-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { randomBytes } from "crypto";\nexport function generateSessionToken() { return randomBytes(8); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-RNG-02");
			expect(finding?.helpUrl).toContain("CS-RNG-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-019 json CS-HASH-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createHash } from "crypto";\nexport function hashPassword(p: string) { return createHash("md5").update(p).digest("hex"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-01");
			expect(finding?.helpUrl).toContain("CS-HASH-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-020 sarif CS-HASH-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createHash } from "crypto";\nexport function hashPassword(p: string) { return createHash("md5").update(p).digest("hex"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-01");
			expect(finding?.helpUrl).toContain("CS-HASH-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-021 json CS-HASH-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import bcrypt from "bcrypt";\nexport function hashPassword(p: string) { return bcrypt.hashSync(p, 8); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-02");
			expect(finding?.helpUrl).toContain("CS-HASH-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-022 sarif CS-HASH-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import bcrypt from "bcrypt";\nexport function hashPassword(p: string) { return bcrypt.hashSync(p, 8); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-02");
			expect(finding?.helpUrl).toContain("CS-HASH-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-023 json CS-HASH-03", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { pbkdf2Sync } from "crypto";\nexport function deriveKeyFromPassword(p: string, s: Buffer) { return pbkdf2Sync(p, s, 1000, 32, "sha256"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-03");
			expect(finding?.helpUrl).toContain("CS-HASH-03");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-024 sarif CS-HASH-03", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { pbkdf2Sync } from "crypto";\nexport function deriveKeyFromPassword(p: string, s: Buffer) { return pbkdf2Sync(p, s, 1000, 32, "sha256"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-03");
			expect(finding?.helpUrl).toContain("CS-HASH-03");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-025 json CS-HASH-04", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { scryptSync } from "crypto";\nexport function hashPassword(p: string, s: Buffer) { return scryptSync(p, s, 64, { cost: 8192 }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-04");
			expect(finding?.helpUrl).toContain("CS-HASH-04");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-026 sarif CS-HASH-04", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { scryptSync } from "crypto";\nexport function hashPassword(p: string, s: Buffer) { return scryptSync(p, s, 64, { cost: 8192 }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-04");
			expect(finding?.helpUrl).toContain("CS-HASH-04");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-027 json CS-HASH-05", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import argon2 from "argon2";\nexport async function hashPassword(p: string) { return argon2.hash(p, { timeCost: 2 }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-05");
			expect(finding?.helpUrl).toContain("CS-HASH-05");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-028 sarif CS-HASH-05", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import argon2 from "argon2";\nexport async function hashPassword(p: string) { return argon2.hash(p, { timeCost: 2 }); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-HASH-05");
			expect(finding?.helpUrl).toContain("CS-HASH-05");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-029 json CS-ENC-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc() { return createCipheriv("aes-256-cbc", "sixteen-byte-key", "1234567890123456"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-01");
			expect(finding?.helpUrl).toContain("CS-ENC-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-030 sarif CS-ENC-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc() { return createCipheriv("aes-256-cbc", "sixteen-byte-key", "1234567890123456"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-01");
			expect(finding?.helpUrl).toContain("CS-ENC-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-031 json CS-ENC-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc(k: Buffer) { return createCipheriv("aes-256-gcm", k, "twelve-byte!"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-02");
			expect(finding?.helpUrl).toContain("CS-ENC-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-032 sarif CS-ENC-02", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc(k: Buffer) { return createCipheriv("aes-256-gcm", k, "twelve-byte!"); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-02");
			expect(finding?.helpUrl).toContain("CS-ENC-02");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-033 json CS-ENC-03", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc(k: Buffer, iv: Buffer) { return createCipheriv("des-cbc", k, iv); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-03");
			expect(finding?.helpUrl).toContain("CS-ENC-03");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-034 sarif CS-ENC-03", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc(k: Buffer, iv: Buffer) { return createCipheriv("des-cbc", k, iv); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-03");
			expect(finding?.helpUrl).toContain("CS-ENC-03");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-035 json CS-ENC-04", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc(k: Buffer, iv: Buffer) { return createCipheriv("aes-128-ecb", k, iv); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-04");
			expect(finding?.helpUrl).toContain("CS-ENC-04");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-036 sarif CS-ENC-04", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createCipheriv } from "crypto";\nexport function enc(k: Buffer, iv: Buffer) { return createCipheriv("aes-128-ecb", k, iv); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-ENC-04");
			expect(finding?.helpUrl).toContain("CS-ENC-04");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-037 json CS-DEC-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createDecipher } from "crypto";\nexport function dec(d: Buffer, p: string) { return createDecipher("aes-256-cbc", p); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-DEC-01");
			expect(finding?.helpUrl).toContain("CS-DEC-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("json" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
	it("CS-V131-REP-038 sarif CS-DEC-01", async () => {
		const dir = fs.mkdtempSync(path.join(os.tmpdir(), "ciphersins-rep-"));
		fs.writeFileSync(
			path.join(dir, "t.ts"),
			'import { createDecipher } from "crypto";\nexport function dec(d: Buffer, p: string) { return createDecipher("aes-256-cbc", p); }\n',
		);
		try {
			const result = await scan({ paths: [path.join(dir, "t.ts")], cwd: dir });
			const finding = result.findings.find((f) => f.ruleId === "CS-DEC-01");
			expect(finding?.helpUrl).toContain("CS-DEC-01");
			const { formatJson, formatSarif, summarizeFindings, VERSION } =
				await import("ciphersins");
			const payload = {
				...result,
				summary: summarizeFindings(result.findings),
			};
			if ("sarif" === "json") {
				expect(
					JSON.parse(formatJson(payload, { cwd: dir, toolVersion: VERSION }))
						.findings.length,
				).toBeGreaterThan(0);
			} else {
				expect(
					JSON.parse(formatSarif(payload, { cwd: dir, toolVersion: VERSION }))
						.runs[0]?.results?.length,
				).toBeGreaterThan(0);
			}
		} finally {
			fs.rmSync(dir, { recursive: true, force: true });
		}
	});
});
