// Auto-generated by scripts/generate-v131-tests.mjs
import { describe, expect, it } from "vitest";
import { countRule, scanSource } from "./helpers/v131-scan-source.js";

describe("CS-V131 suppressions exhaustive", () => {
	it("CS-V131-SUP-001 suppress next-line CS-JWT-01", async () => {
		const result = await scanSource(
			"sup-001.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string) {\n  // ciphersins-ignore-next-line CS-JWT-01\n  return jwt.decode(t);\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-01";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-002 wrong suppress id still flags CS-JWT-01", async () => {
		const result = await scanSource(
			"sup-002.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return jwt.decode(t);\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-01";
		const expected = { "CS-JWT-01": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-003 suppress next-line CS-JWT-02", async () => {
		const result = await scanSource(
			"sup-003.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-02\n  return jwt.verify(t, s);\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-02";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-004 wrong suppress id still flags CS-JWT-02", async () => {
		const result = await scanSource(
			"sup-004.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return jwt.verify(t, s);\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-02";
		const expected = { "CS-JWT-02": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-005 suppress next-line CS-JWT-03", async () => {
		const result = await scanSource(
			"sup-005.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-03\n  return jwt.verify(t, s, { algorithms: ["none"] });\n}\n',
			{ scan: { allowCriticalIgnore: true } },
		);
		const ruleId = "CS-JWT-03";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-006 wrong suppress id still flags CS-JWT-03", async () => {
		const result = await scanSource(
			"sup-006.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return jwt.verify(t, s, { algorithms: ["none"] });\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-03";
		const expected = { "CS-JWT-03": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-007 suppress next-line CS-JWT-04", async () => {
		const result = await scanSource(
			"sup-007.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-04\n  return jwt.verify(t, s, { ignoreExpiration: true, algorithms: ["HS256"] });\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-04";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-008 wrong suppress id still flags CS-JWT-04", async () => {
		const result = await scanSource(
			"sup-008.ts",
			'import jwt from "jsonwebtoken";\nexport function f(t: string, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return jwt.verify(t, s, { ignoreExpiration: true, algorithms: ["HS256"] });\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-04";
		const expected = { "CS-JWT-04": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-009 suppress next-line CS-JWT-05", async () => {
		const result = await scanSource(
			"sup-009.ts",
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-05\n  return jwt.sign(p, s);\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-05";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-010 wrong suppress id still flags CS-JWT-05", async () => {
		const result = await scanSource(
			"sup-010.ts",
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return jwt.sign(p, s);\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-05";
		const expected = { "CS-JWT-05": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-011 suppress next-line CS-JWT-06", async () => {
		const result = await scanSource(
			"sup-011.ts",
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-06\n  return jwt.sign(p, s, { noTimestamp: true });\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-06";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-012 wrong suppress id still flags CS-JWT-06", async () => {
		const result = await scanSource(
			"sup-012.ts",
			'import jwt from "jsonwebtoken";\nexport function f(p: object, s: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return jwt.sign(p, s, { noTimestamp: true });\n}\n',
			undefined,
		);
		const ruleId = "CS-JWT-06";
		const expected = { "CS-JWT-06": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-013 suppress next-line CS-CMP-01", async () => {
		const result = await scanSource(
			"sup-013.ts",
			'import crypto from "crypto";\nexport function f(token: string, expected: string) {\n  // ciphersins-ignore-next-line CS-CMP-01\n  return token === expected;\n}\n',
			undefined,
		);
		const ruleId = "CS-CMP-01";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-014 wrong suppress id still flags CS-CMP-01", async () => {
		const result = await scanSource(
			"sup-014.ts",
			'import crypto from "crypto";\nexport function f(token: string, expected: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return token === expected;\n}\n',
			undefined,
		);
		const ruleId = "CS-CMP-01";
		const expected = { "CS-CMP-01": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-015 suppress next-line CS-RNG-01", async () => {
		const result = await scanSource(
			"sup-015.ts",
			"export function generateToken() {\n  // ciphersins-ignore-next-line CS-RNG-01\n  return Math.random();\n}\n",
			undefined,
		);
		const ruleId = "CS-RNG-01";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-016 wrong suppress id still flags CS-RNG-01", async () => {
		const result = await scanSource(
			"sup-016.ts",
			"export function generateToken() {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return Math.random();\n}\n",
			undefined,
		);
		const ruleId = "CS-RNG-01";
		const expected = { "CS-RNG-01": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-017 suppress next-line CS-RNG-02", async () => {
		const result = await scanSource(
			"sup-017.ts",
			'import { randomBytes } from "crypto";\nexport function generateSessionToken() {\n  // ciphersins-ignore-next-line CS-RNG-02\n  return randomBytes(8);\n}\n',
			undefined,
		);
		const ruleId = "CS-RNG-02";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-018 wrong suppress id still flags CS-RNG-02", async () => {
		const result = await scanSource(
			"sup-018.ts",
			'import { randomBytes } from "crypto";\nexport function generateSessionToken() {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return randomBytes(8);\n}\n',
			undefined,
		);
		const ruleId = "CS-RNG-02";
		const expected = { "CS-RNG-02": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-019 suppress next-line CS-HASH-01", async () => {
		const result = await scanSource(
			"sup-019.ts",
			'import { createHash } from "crypto";\nexport function hashPassword(p: string) {\n  // ciphersins-ignore-next-line CS-HASH-01\n  return createHash("md5").update(p).digest("hex");\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-01";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-020 wrong suppress id still flags CS-HASH-01", async () => {
		const result = await scanSource(
			"sup-020.ts",
			'import { createHash } from "crypto";\nexport function hashPassword(p: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return createHash("md5").update(p).digest("hex");\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-01";
		const expected = { "CS-HASH-01": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-021 suppress next-line CS-HASH-02", async () => {
		const result = await scanSource(
			"sup-021.ts",
			'import bcrypt from "bcrypt";\nexport function hashPassword(p: string) {\n  // ciphersins-ignore-next-line CS-HASH-02\n  return bcrypt.hashSync(p, 8);\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-02";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-022 wrong suppress id still flags CS-HASH-02", async () => {
		const result = await scanSource(
			"sup-022.ts",
			'import bcrypt from "bcrypt";\nexport function hashPassword(p: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return bcrypt.hashSync(p, 8);\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-02";
		const expected = { "CS-HASH-02": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-023 suppress next-line CS-HASH-03", async () => {
		const result = await scanSource(
			"sup-023.ts",
			'import { pbkdf2Sync } from "crypto";\nexport function deriveKeyFromPassword(p: string, s: Buffer) {\n  // ciphersins-ignore-next-line CS-HASH-03\n  return pbkdf2Sync(p, s, 1000, 32, "sha256");\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-03";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-024 wrong suppress id still flags CS-HASH-03", async () => {
		const result = await scanSource(
			"sup-024.ts",
			'import { pbkdf2Sync } from "crypto";\nexport function deriveKeyFromPassword(p: string, s: Buffer) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return pbkdf2Sync(p, s, 1000, 32, "sha256");\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-03";
		const expected = { "CS-HASH-03": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-025 suppress next-line CS-HASH-04", async () => {
		const result = await scanSource(
			"sup-025.ts",
			'import { scryptSync } from "crypto";\nexport function hashPassword(p: string, s: Buffer) {\n  // ciphersins-ignore-next-line CS-HASH-04\n  return scryptSync(p, s, 64, { cost: 8192 });\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-04";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-026 wrong suppress id still flags CS-HASH-04", async () => {
		const result = await scanSource(
			"sup-026.ts",
			'import { scryptSync } from "crypto";\nexport function hashPassword(p: string, s: Buffer) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return scryptSync(p, s, 64, { cost: 8192 });\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-04";
		const expected = { "CS-HASH-04": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-027 suppress next-line CS-HASH-05", async () => {
		const result = await scanSource(
			"sup-027.ts",
			'import argon2 from "argon2";\nexport async function hashPassword(p: string) {\n  // ciphersins-ignore-next-line CS-HASH-05\n  return argon2.hash(p, { timeCost: 2 });\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-05";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-028 wrong suppress id still flags CS-HASH-05", async () => {
		const result = await scanSource(
			"sup-028.ts",
			'import argon2 from "argon2";\nexport async function hashPassword(p: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return argon2.hash(p, { timeCost: 2 });\n}\n',
			undefined,
		);
		const ruleId = "CS-HASH-05";
		const expected = { "CS-HASH-05": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-029 suppress next-line CS-ENC-01", async () => {
		const result = await scanSource(
			"sup-029.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer) {\n  // ciphersins-ignore-next-line CS-ENC-01\n  return createCipheriv("aes-256-cbc", "sixteen-byte-key", "1234567890123456");\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-01";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-030 wrong suppress id still flags CS-ENC-01", async () => {
		const result = await scanSource(
			"sup-030.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return createCipheriv("aes-256-cbc", "sixteen-byte-key", "1234567890123456");\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-01";
		const expected = { "CS-ENC-01": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-031 suppress next-line CS-ENC-02", async () => {
		const result = await scanSource(
			"sup-031.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer, k: Buffer) {\n  // ciphersins-ignore-next-line CS-ENC-02\n  return createCipheriv("aes-256-gcm", k, "twelve-byte!");\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-02";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-032 wrong suppress id still flags CS-ENC-02", async () => {
		const result = await scanSource(
			"sup-032.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer, k: Buffer) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return createCipheriv("aes-256-gcm", k, "twelve-byte!");\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-02";
		const expected = { "CS-ENC-02": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-033 suppress next-line CS-ENC-03", async () => {
		const result = await scanSource(
			"sup-033.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer, k: Buffer, iv: Buffer) {\n  // ciphersins-ignore-next-line CS-ENC-03\n  return createCipheriv("des-cbc", k, iv);\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-03";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-034 wrong suppress id still flags CS-ENC-03", async () => {
		const result = await scanSource(
			"sup-034.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer, k: Buffer, iv: Buffer) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return createCipheriv("des-cbc", k, iv);\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-03";
		const expected = { "CS-ENC-03": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-035 suppress next-line CS-ENC-04", async () => {
		const result = await scanSource(
			"sup-035.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer, k: Buffer, iv: Buffer) {\n  // ciphersins-ignore-next-line CS-ENC-04\n  return createCipheriv("aes-128-ecb", k, iv);\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-04";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-036 wrong suppress id still flags CS-ENC-04", async () => {
		const result = await scanSource(
			"sup-036.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(d: Buffer, k: Buffer, iv: Buffer) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return createCipheriv("aes-128-ecb", k, iv);\n}\n',
			undefined,
		);
		const ruleId = "CS-ENC-04";
		const expected = { "CS-ENC-04": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-037 suppress next-line CS-DEC-01", async () => {
		const result = await scanSource(
			"sup-037.ts",
			'import { createDecipher } from "crypto";\nexport function dec(d: Buffer, p: string) {\n  // ciphersins-ignore-next-line CS-DEC-01\n  return createDecipher("aes-256-cbc", p);\n}\n',
			undefined,
		);
		const ruleId = "CS-DEC-01";
		const expected = {};
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});

	it("CS-V131-SUP-038 wrong suppress id still flags CS-DEC-01", async () => {
		const result = await scanSource(
			"sup-038.ts",
			'import { createDecipher } from "crypto";\nexport function dec(d: Buffer, p: string) {\n  // ciphersins-ignore-next-line CS-JWT-99\n  return createDecipher("aes-256-cbc", p);\n}\n',
			undefined,
		);
		const ruleId = "CS-DEC-01";
		const expected = { "CS-DEC-01": 1 };
		for (const [id, count] of Object.entries(expected)) {
			expect(countRule(result.findings, id)).toBe(count);
		}
		if (Object.keys(expected).length === 0 && ruleId) {
			expect(countRule(result.findings, ruleId)).toBe(0);
		}
	});
});
