// Auto-generated by scripts/generate-v131-tests.mjs — do not edit by hand
import { describe, expect, it } from "vitest";
import { countRule, scanSource } from "../helpers/v131-scan-source.js";

describe("CS-V131 HLP-SCAN exhaustive edge cases", () => {
	it("CS-V131-HLP-SCAN-HLP-001 auth name token rng01", async () => {
		const result = await scanSource(
			"case-HLP-001.ts",
			"export function generateToken() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-002 auth name accessToken rng01", async () => {
		const result = await scanSource(
			"case-HLP-002.ts",
			"export function generateAccessToken() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-003 auth name refreshToken rng01", async () => {
		const result = await scanSource(
			"case-HLP-003.ts",
			"export function generateRefreshToken() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-004 auth name sessionSecret rng01", async () => {
		const result = await scanSource(
			"case-HLP-004.ts",
			"export function generateSessionSecret() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-005 auth name password rng01", async () => {
		const result = await scanSource(
			"case-HLP-005.ts",
			"export function generatePassword() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-006 auth name otp rng01", async () => {
		const result = await scanSource(
			"case-HLP-006.ts",
			"export function generateOtp() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-007 auth name csrfToken rng01", async () => {
		const result = await scanSource(
			"case-HLP-007.ts",
			"export function generateCsrfToken() {\n  return Math.random();\n}\n",
		);
		const expected = { "CS-RNG-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-008 non-auth username rng clean", async () => {
		const result = await scanSource(
			"case-HLP-008.ts",
			"export function pickUsername() {\n  return Math.random();\n}\n",
		);
		const expected = {};
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-009 non-auth hashtag rng clean", async () => {
		const result = await scanSource(
			"case-HLP-009.ts",
			"export function pickHashtag() {\n  return Math.random();\n}\n",
		);
		const expected = {};
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-010 non-auth author rng clean", async () => {
		const result = await scanSource(
			"case-HLP-010.ts",
			"export function pickAuthor() {\n  return Math.random();\n}\n",
		);
		const expected = {};
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-011 non-auth publisher rng clean", async () => {
		const result = await scanSource(
			"case-HLP-011.ts",
			"export function pickPublisher() {\n  return Math.random();\n}\n",
		);
		const expected = {};
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-012 non-auth color rng clean", async () => {
		const result = await scanSource(
			"case-HLP-012.ts",
			"export function pickColor() {\n  return Math.random();\n}\n",
		);
		const expected = {};
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-013 password ctx hashPassword md5", async () => {
		const result = await scanSource(
			"case-HLP-013.ts",
			'import { createHash } from "crypto";\nexport function hashPassword(password: string) {\n  return createHash("md5").update(password).digest("hex");\n}',
		);
		const expected = { "CS-HASH-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-014 password ctx verifyPassword md5", async () => {
		const result = await scanSource(
			"case-HLP-014.ts",
			'import { createHash } from "crypto";\nexport function verifyPassword(password: string) {\n  return createHash("md5").update(password).digest("hex");\n}',
		);
		const expected = { "CS-HASH-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-015 password ctx deriveKeyFromPassword md5", async () => {
		const result = await scanSource(
			"case-HLP-015.ts",
			'import { createHash } from "crypto";\nexport function deriveKeyFromPassword(password: string) {\n  return createHash("md5").update(password).digest("hex");\n}',
		);
		const expected = { "CS-HASH-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-HLP-SCAN-HLP-016 password ctx checkPassphrase md5", async () => {
		const result = await scanSource(
			"case-HLP-016.ts",
			'import { createHash } from "crypto";\nexport function checkPassphrase(password: string) {\n  return createHash("md5").update(password).digest("hex");\n}',
		);
		const expected = { "CS-HASH-01": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});
});
