// Auto-generated by scripts/generate-v131-tests.mjs — do not edit by hand
import { describe, expect, it } from "vitest";
import { countRule, scanSource } from "../helpers/v131-scan-source.js";

describe("CS-V131 INT exhaustive edge cases", () => {
	it("CS-V131-INT-001 pbkdf2 md5 1000 iter variant 1", async () => {
		const result = await scanSource(
			"case-001.ts",
			'import { pbkdf2Sync } from "crypto";\nexport function derive(password: string, salt: Buffer) {\n  return pbkdf2Sync(password, salt, 1000, 32, "md5");\n}',
		);
		const expected = { "CS-HASH-01": 1, "CS-HASH-03": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-002 pbkdf2 md5 1000 iter variant 2", async () => {
		const result = await scanSource(
			"case-002.ts",
			'import { pbkdf2Sync } from "crypto";\nexport function derive(password: string, salt: Buffer) {\n  return pbkdf2Sync(password, salt, 1000, 32, "md5");\n}',
		);
		const expected = { "CS-HASH-01": 1, "CS-HASH-03": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-003 pbkdf2 md5 1000 iter variant 3", async () => {
		const result = await scanSource(
			"case-003.ts",
			'import { pbkdf2Sync } from "crypto";\nexport function derive(password: string, salt: Buffer) {\n  return pbkdf2Sync(password, salt, 1000, 32, "md5");\n}',
		);
		const expected = { "CS-HASH-01": 1, "CS-HASH-03": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-004 scrypt low cost only variant 1", async () => {
		const result = await scanSource(
			"case-004.ts",
			'import { scryptSync } from "crypto";\nexport function hashPassword(pwd: string, salt: Buffer) {\n  return scryptSync(pwd, salt, 64, { cost: 8192, blockSize: 8 });\n}',
		);
		const expected = { "CS-HASH-04": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-005 scrypt low cost only variant 2", async () => {
		const result = await scanSource(
			"case-005.ts",
			'import { scryptSync } from "crypto";\nexport function hashPassword(pwd: string, salt: Buffer) {\n  return scryptSync(pwd, salt, 64, { cost: 8192, blockSize: 8 });\n}',
		);
		const expected = { "CS-HASH-04": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-006 scrypt low cost only variant 3", async () => {
		const result = await scanSource(
			"case-006.ts",
			'import { scryptSync } from "crypto";\nexport function hashPassword(pwd: string, salt: Buffer) {\n  return scryptSync(pwd, salt, 64, { cost: 8192, blockSize: 8 });\n}',
		);
		const expected = { "CS-HASH-04": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-007 argon2 low timeCost only variant 1", async () => {
		const result = await scanSource(
			"case-007.ts",
			'import argon2 from "argon2";\nexport async function hashPassword(password: string) {\n  return argon2.hash(password, { timeCost: 2, memoryCost: 65536 });\n}',
		);
		const expected = { "CS-HASH-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-008 argon2 low timeCost only variant 2", async () => {
		const result = await scanSource(
			"case-008.ts",
			'import argon2 from "argon2";\nexport async function hashPassword(password: string) {\n  return argon2.hash(password, { timeCost: 2, memoryCost: 65536 });\n}',
		);
		const expected = { "CS-HASH-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-009 argon2 low timeCost only variant 3", async () => {
		const result = await scanSource(
			"case-009.ts",
			'import argon2 from "argon2";\nexport async function hashPassword(password: string) {\n  return argon2.hash(password, { timeCost: 2, memoryCost: 65536 });\n}',
		);
		const expected = { "CS-HASH-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-010 des hardcoded key enc01+enc03 variant 1", async () => {
		const result = await scanSource(
			"case-010.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(data: Buffer) {\n  return createCipheriv("des-cbc", "12345678", "12345678");\n}',
		);
		const expected = { "CS-ENC-01": 1, "CS-ENC-03": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-011 des hardcoded key enc01+enc03 variant 2", async () => {
		const result = await scanSource(
			"case-011.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(data: Buffer) {\n  return createCipheriv("des-cbc", "12345678", "12345678");\n}',
		);
		const expected = { "CS-ENC-01": 1, "CS-ENC-03": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-012 des hardcoded key enc01+enc03 variant 3", async () => {
		const result = await scanSource(
			"case-012.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(data: Buffer) {\n  return createCipheriv("des-cbc", "12345678", "12345678");\n}',
		);
		const expected = { "CS-ENC-01": 1, "CS-ENC-03": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-013 ecb hardcoded enc01+enc04 variant 1", async () => {
		const result = await scanSource(
			"case-013.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(data: Buffer) {\n  return createCipheriv("aes-128-ecb", "1234567890123456", Buffer.alloc(0));\n}',
		);
		const expected = { "CS-ENC-01": 1, "CS-ENC-04": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-014 ecb hardcoded enc01+enc04 variant 2", async () => {
		const result = await scanSource(
			"case-014.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(data: Buffer) {\n  return createCipheriv("aes-128-ecb", "1234567890123456", Buffer.alloc(0));\n}',
		);
		const expected = { "CS-ENC-01": 1, "CS-ENC-04": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-015 ecb hardcoded enc01+enc04 variant 3", async () => {
		const result = await scanSource(
			"case-015.ts",
			'import { createCipheriv } from "crypto";\nexport function enc(data: Buffer) {\n  return createCipheriv("aes-128-ecb", "1234567890123456", Buffer.alloc(0));\n}',
		);
		const expected = { "CS-ENC-01": 1, "CS-ENC-04": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-016 sign no expiry jwt05 variant 1", async () => {
		const result = await scanSource(
			"case-016.ts",
			'import jwt from "jsonwebtoken";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s);\n}',
		);
		const expected = { "CS-JWT-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-017 sign no expiry jwt05 variant 2", async () => {
		const result = await scanSource(
			"case-017.ts",
			'import jwt from "jsonwebtoken";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s);\n}',
		);
		const expected = { "CS-JWT-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-018 sign no expiry jwt05 variant 3", async () => {
		const result = await scanSource(
			"case-018.ts",
			'import jwt from "jsonwebtoken";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s);\n}',
		);
		const expected = { "CS-JWT-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-019 noTimestamp no expiry jwt05+jwt06 variant 1", async () => {
		const result = await scanSource(
			"case-019.ts",
			'import jwt from "jsonwebtoken";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s, { noTimestamp: true });\n}',
		);
		const expected = { "CS-JWT-05": 1, "CS-JWT-06": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-020 noTimestamp no expiry jwt05+jwt06 variant 2", async () => {
		const result = await scanSource(
			"case-020.ts",
			'import jwt from "jsonwebtoken";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s, { noTimestamp: true });\n}',
		);
		const expected = { "CS-JWT-05": 1, "CS-JWT-06": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-021 noTimestamp no expiry jwt05+jwt06 variant 3", async () => {
		const result = await scanSource(
			"case-021.ts",
			'import jwt from "jsonwebtoken";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s, { noTimestamp: true });\n}',
		);
		const expected = { "CS-JWT-05": 1, "CS-JWT-06": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-022 sign none no expiry jwt03+jwt05 variant 1", async () => {
		const result = await scanSource(
			"case-022.ts",
			"import jwt from \"jsonwebtoken\";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s, { algorithm: 'none' });\n}",
		);
		const expected = { "CS-JWT-03": 1, "CS-JWT-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-023 sign none no expiry jwt03+jwt05 variant 2", async () => {
		const result = await scanSource(
			"case-023.ts",
			"import jwt from \"jsonwebtoken\";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s, { algorithm: 'none' });\n}",
		);
		const expected = { "CS-JWT-03": 1, "CS-JWT-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-024 sign none no expiry jwt03+jwt05 variant 3", async () => {
		const result = await scanSource(
			"case-024.ts",
			"import jwt from \"jsonwebtoken\";\nexport function issue(p: object, s: string) {\n  return jwt.sign(p, s, { algorithm: 'none' });\n}",
		);
		const expected = { "CS-JWT-03": 1, "CS-JWT-05": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-025 rng01+rng02 auth fn variant 1", async () => {
		const result = await scanSource(
			"case-025.ts",
			"import { randomBytes } from \"crypto\";\nexport function generateSessionToken() {\n  return Math.random().toString(36) + randomBytes(4).toString('hex');\n}",
		);
		const expected = { "CS-RNG-01": 1, "CS-RNG-02": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-026 rng01+rng02 auth fn variant 2", async () => {
		const result = await scanSource(
			"case-026.ts",
			"import { randomBytes } from \"crypto\";\nexport function generateSessionToken() {\n  return Math.random().toString(36) + randomBytes(4).toString('hex');\n}",
		);
		const expected = { "CS-RNG-01": 1, "CS-RNG-02": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-027 rng01+rng02 auth fn variant 3", async () => {
		const result = await scanSource(
			"case-027.ts",
			"import { randomBytes } from \"crypto\";\nexport function generateSessionToken() {\n  return Math.random().toString(36) + randomBytes(4).toString('hex');\n}",
		);
		const expected = { "CS-RNG-01": 1, "CS-RNG-02": 1 };
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});

	it("CS-V131-INT-028 INT clean bcrypt strong + jwt verify alg", async () => {
		const result = await scanSource(
			"case-028.ts",
			'import bcrypt from "bcrypt";\nimport jwt from "jsonwebtoken";\nexport async function login(password: string, hash: string, token: string, secret: string) {\n  bcrypt.compareSync(password, hash);\n  return jwt.verify(token, secret, { algorithms: [\'HS256\'] });\n}',
		);
		const expected = {};
		for (const [ruleId, count] of Object.entries(expected)) {
			expect(countRule(result.findings, ruleId)).toBe(count);
		}
		if (Object.keys(expected).length === 0) {
			expect(result.findings).toEqual([]);
		} else {
			const expectedTotal = Object.values(expected).reduce((a, b) => a + b, 0);
			expect(result.findings.length).toBeGreaterThanOrEqual(expectedTotal);
		}
	});
});
