#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

function syncPackageVersion(relativePath) {
	const packageJsonPath = path.join(rootDir, relativePath, "package.json");
	const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, "utf8"));
	const versionPath = path.join(rootDir, relativePath, "src/version.ts");
	fs.writeFileSync(
		versionPath,
		`// Generated by scripts/sync-version.mjs — do not edit.\nexport const VERSION = ${JSON.stringify(packageJson.version)};\n`,
	);
	return packageJson.version;
}

const coreVersion = syncPackageVersion("packages/core");
syncPackageVersion("packages/cli");

const cliPackageJsonPath = path.join(rootDir, "packages/cli/package.json");
const cliPackageJson = JSON.parse(fs.readFileSync(cliPackageJsonPath, "utf8"));
cliPackageJson.dependencies["@ciphersins/core"] = coreVersion;
fs.writeFileSync(
	cliPackageJsonPath,
	`${JSON.stringify(cliPackageJson, null, "\t")}\n`,
);
