// Auto-generated by scripts/generate-v131-tests.mjs
import { spawnSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(testDir, "../..");
const cliEntry = path.join(rootDir, "packages/ciphersins/dist/cli.js");

describe("CS-V131 CLI exhaustive expanded", () => {
	it("CS-V131-CLI-001 jwt01 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-01",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-002 jwt01 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-01",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-003 jwt01 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-01",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-004 jwt02 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-02",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-005 jwt02 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-02",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-006 jwt02 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-02",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-007 jwt03 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-03",
				"--format",
				"json",
				"--fail-on",
				"critical",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-008 jwt03 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-03",
				"--format",
				"pretty",
				"--fail-on",
				"critical",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-009 jwt03 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-03",
				"--format",
				"sarif",
				"--fail-on",
				"critical",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-010 jwt04 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-04",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-011 jwt04 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-04",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-012 jwt04 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-04",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-013 jwt05 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-05/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-05",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-014 jwt05 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-05/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-05",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-015 jwt05 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-05/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-05",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-016 jwt06 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-06/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-06",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-017 jwt06 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-06/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-06",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-018 jwt06 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-06/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-JWT-06",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-019 cmp01 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-cmp-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-CMP-01",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-020 cmp01 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-cmp-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-CMP-01",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-021 cmp01 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-cmp-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-CMP-01",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-022 rng01 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-rng-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-RNG-01",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-023 rng01 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-rng-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-RNG-01",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-024 rng01 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-rng-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-RNG-01",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-025 rng02 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-rng-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-RNG-02",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-026 rng02 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-rng-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-RNG-02",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-027 rng02 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-rng-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-RNG-02",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-028 hash01 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-01",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-029 hash01 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-01",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-030 hash01 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-01",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-031 hash02 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-02",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-032 hash02 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-02",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-033 hash02 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-02",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-034 hash03 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-03",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-035 hash03 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-03",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-036 hash03 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-03",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-037 hash04 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-04",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-038 hash04 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-04",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-039 hash04 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-04",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-040 hash05 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-05/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-05",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-041 hash05 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-05/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-05",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-042 hash05 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-hash-05/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-HASH-05",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-043 enc01 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-01",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-044 enc01 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-01",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-045 enc01 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-01",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-046 enc02 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-02",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-047 enc02 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-02",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-048 enc02 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-02/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-02",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-049 enc03 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-03",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-050 enc03 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-03",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-051 enc03 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-03/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-03",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-052 enc04 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-04",
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-053 enc04 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-04",
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-054 enc04 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-04/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-ENC-04",
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-055 dec01 bad format json", () => {
		const dir = path.join(rootDir, "fixtures/cs-dec-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-DEC-01",
				"--format",
				"json",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-056 dec01 bad format pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-dec-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-DEC-01",
				"--format",
				"pretty",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-057 dec01 bad format sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-dec-01/bad");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--only",
				"CS-DEC-01",
				"--format",
				"sarif",
				"--fail-on",
				"medium",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(1);
	});
	it("CS-V131-CLI-058 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-01/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-059 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-01/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-060 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-01/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-061 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-02/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-062 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-02/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-063 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-02/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-064 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-03/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-065 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-03/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-066 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-03/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-067 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-04/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-068 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-04/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-069 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-04/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-070 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-05/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-071 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-05/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-072 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-05/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-073 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-06/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-074 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-06/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-075 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-jwt-06/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-076 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-01/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-077 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-01/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-078 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-01/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-079 good good fmt json", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-02/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"json",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-080 good good fmt pretty", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-02/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"pretty",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
	it("CS-V131-CLI-081 good good fmt sarif", () => {
		const dir = path.join(rootDir, "fixtures/cs-enc-02/good");
		const result = spawnSync(
			process.execPath,
			[
				cliEntry,
				"scan",
				dir,
				"--format",
				"sarif",
				"--fail-on",
				"high",
				"--no-color",
			],
			{
				encoding: "utf8",
				cwd: rootDir,
			},
		);
		expect(result.status).toBe(0);
	});
});
